"""create tasks table

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 23:40:20.052836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('task', 'exam', name='task_type'), server_default='task', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(trim(title)) > 0', name=op.f('ck_tasks_title_not_blank')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_tasks_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_subject_id_due_at_active', 'tasks', ['subject_id', 'due_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_subject_id_due_at_active', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('tasks')
    # ### end Alembic commands ###
    # Alembic no elimina los ENUM al borrar la tabla que los usa.
    sa.Enum(name='task_type').drop(op.get_bind(), checkfirst=True)
