"""create remaining tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 23:52:12.165673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pending_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pending_action_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(pending_action IS NULL) = (pending_action_expires_at IS NULL)', name=op.f('ck_conversations_pending_action_consistent')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_conversations'))
    )
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_login_attempts'))
    )
    op.create_index('ix_failed_login_attempts_email_attempted_at', 'failed_login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('custom_message', sa.String(length=500), nullable=True),
    sa.Column('origin', sa.Enum('automatic', 'custom', name='reminder_origin'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'cancelled', name='reminder_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index('ix_reminders_scheduled_at_pending', 'reminders', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index(op.f('ix_reminders_task_id'), 'reminders', ['task_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'discarded', name='study_plan_status'), server_default='proposed', nullable=False),
    sa.Column('preference', sa.Enum('between_classes', 'after_classes', 'both', name='study_preference'), nullable=False),
    sa.Column('window_start', sa.Time(), server_default=sa.text("'06:00'"), nullable=False),
    sa.Column('window_end', sa.Time(), server_default=sa.text("'22:00'"), nullable=False),
    sa.Column('session_minutes', sa.SmallInteger(), server_default=sa.text('60'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("window_start >= '05:00' AND window_end <= '23:00' AND window_end > window_start", name=op.f('ck_study_plans_window_within_limits')),
    sa.CheckConstraint('session_minutes > 0', name=op.f('ck_study_plans_session_minutes_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans'))
    )
    op.create_index('uq_study_plans_user_id_accepted', 'study_plans', ['user_id'], unique=True, postgresql_where=sa.text("status = 'accepted'"))
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['conversations.user_id'], name=op.f('fk_conversation_messages_user_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index('ix_conversation_messages_user_id_created_at', 'conversation_messages', ['user_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reminder_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('push_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('push_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('push_attempts BETWEEN 0 AND 4', name=op.f('ck_notifications_push_attempts_range')),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_notifications_reminder_id_reminders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('reminder_id', name=op.f('uq_notifications_reminder_id'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_password_reset_tokens_expires_after_created')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index('ix_password_reset_tokens_user_id_created_at', 'password_reset_tokens', ['user_id', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('fcm_token', name=op.f('uq_sessions_fcm_token'))
    )
    op.create_index('ix_sessions_user_id_active', 'sessions', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('study_plan_days',
    sa.Column('study_plan_id', sa.Uuid(), nullable=False),
    # El ENUM weekday ya existe desde la migración 0002.
    sa.Column('weekday', postgresql.ENUM(name='weekday', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], name=op.f('fk_study_plan_days_study_plan_id_study_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_plan_id', 'weekday', name=op.f('pk_study_plan_days'))
    )
    op.create_table('study_plan_subjects',
    sa.Column('study_plan_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], name=op.f('fk_study_plan_subjects_study_plan_id_study_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_study_plan_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_plan_id', 'subject_id', name=op.f('pk_study_plan_subjects'))
    )
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_telegram_link_codes_expires_after_created')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_link_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_link_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_telegram_link_codes_code_hash'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_refresh_tokens_expires_after_created')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_plan_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(task_id IS NULL) <> (subject_id IS NULL)', name=op.f('ck_study_sessions_task_xor_subject')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_study_sessions_ends_after_starts')),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], name=op.f('fk_study_sessions_study_plan_id_study_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_study_sessions_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_study_sessions_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index('ix_study_sessions_study_plan_id_starts_at', 'study_sessions', ['study_plan_id', 'starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_sessions_study_plan_id_starts_at', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_table('refresh_tokens')
    op.drop_table('telegram_link_codes')
    op.drop_table('study_plan_subjects')
    op.drop_table('study_plan_days')
    op.drop_index('ix_sessions_user_id_active', table_name='sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('sessions')
    op.drop_index('ix_password_reset_tokens_user_id_created_at', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_index('ix_conversation_messages_user_id_created_at', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('uq_study_plans_user_id_accepted', table_name='study_plans', postgresql_where=sa.text("status = 'accepted'"))
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_task_id'), table_name='reminders')
    op.drop_index('ix_reminders_scheduled_at_pending', table_name='reminders', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('reminders')
    op.drop_index('ix_failed_login_attempts_email_attempted_at', table_name='failed_login_attempts')
    op.drop_table('failed_login_attempts')
    op.drop_table('conversations')
    # ### end Alembic commands ###
    # Alembic no elimina los ENUM al borrar las tablas que los usan.
    for enum_name in ('reminder_origin', 'reminder_status', 'study_plan_status', 'study_preference', 'message_role'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
